spring.application.name=expedix
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5444/expedixdb
spring.datasource.username=ramaiana
spring.datasource.password=ramaiana_password1337
spring.jpa.hibernate.ddl-auto=update
spring.flyway.default-schema=expedix
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
jwt.secret=3gQ5T5eybTz7Kp1y3XzTQBlpY9b1s5Pv4W4eT3Gy6zJzA9MZK7U9P4g1sTzR9Hk2iD7yX8nZ5xB0cT7nU1uN3zE9jF2vC6mL5sJ2oC3wL8rT9kM=
jwt.lifetime = 360000
jwt.expiration = 103600000

