spring.application.name=expedix


spring.datasource.url=jdbc:postgresql://localhost:5444/expedixdb
spring.datasource.username=ramaiana
spring.datasource.password=ramaiana_password1337

spring.jpa.hibernate.ddl-auto=update
spring.flyway.default-schema=expedix