spring.application.name=expedix
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5444/expedixdb
spring.datasource.username=ramaiana
spring.datasource.password=ramaiana_password1337

spring.jpa.hibernate.ddl-auto=update
spring.flyway.default-schema=expedix

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
